### ISSUE TITLE
rpd method no longer works

### ISSUE THREAD

**Issue by xxx** [kristianmandrup/geo-distance#3]
Hi,

We just upgraded geo-distance from v. 1.2 to 2.2, and now we're seeing a failure where the `rpd` method no longer works, though I realize that haversine.rb hasn't changed in a very long time.

```
NoMethodError: undefined method `rpd' for 3.552713678800501e-14:Float
/Users/mpd/.rvm/gems/ruby-2.1.7/gems/geo-distance-0.2.2/lib/geo-distance/formula/haversine.rb:52:in `distance'
```

**Comment by kristianmandrup** [comment]
Im awfully sorry. I no longer work or do support on any of these gems as I no longer use ruby or do any code/development... Taking a (very?) long break. You are welcome to debug and submit patches or take over this/these gems if you like. Thanks.

**Comment by gerrywastaken** [comment]
@kristianmandrup Can you add this to the top of the readme for the project?

**Comment by slicksammy** [comment]
Yeah got the same issue

**Comment by kristianmandrup** [comment]
I'm building a house in France at moment. Would welcome a PR I can merge, with the the `rpd` fix and note on project status in the Readme. Thanks.
